import docx

doc = docx.Document()
doc.add_paragraph("Name:")
doc.add_paragraph("Rahul Kumar")
doc.add_paragraph("")
doc.add_paragraph("Skills:")
doc.add_paragraph("Python")
doc.add_paragraph("Java")
doc.add_paragraph("SQL")
doc.add_paragraph("")
doc.add_paragraph("Experience:")
doc.add_paragraph("2022–2025")
doc.add_paragraph("Software Engineer")
doc.add_paragraph("")
doc.add_paragraph("Education:")
doc.add_paragraph("B.E. Computer Science")
doc.add_paragraph("ABC University")
doc.add_paragraph("2025")

doc.save("tests/fixtures/e2e_resume.docx")

doc2 = docx.Document()
doc2.add_paragraph("Name:")
doc2.add_paragraph("Rahul Kumar")
doc2.add_paragraph("")
doc2.add_paragraph("Skills:")
doc2.add_paragraph("Python")
doc2.add_paragraph("Java")
doc2.add_paragraph("SQL")
doc2.add_paragraph("Docker")
doc2.add_paragraph("AWS")
doc2.add_paragraph("")
doc2.add_paragraph("Experience:")
doc2.add_paragraph("2022–2025")
doc2.add_paragraph("Software Engineer")
doc2.add_paragraph("")
doc2.add_paragraph("Education:")
doc2.add_paragraph("B.E. Computer Science")
doc2.add_paragraph("ABC University")
doc2.add_paragraph("2025")

doc2.save("tests/fixtures/e2e_resume_updated.docx")
